[build]
  command = "npm run build"
  publish = "dist/client"

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set immutable caching for static files, because they have fingerprinted filenames
[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

# These are only used to set up the template, and are not used in the build
# If you want to update the real values, change them in the site UI or CLI
[template.environment]
PUBLIC_STORE_DOMAIN = "mock.shop"
SESSION_SECRET = "mock.shop"
